name: DutyToggle
version: ${project.version}
main: me.junny.dutytoggle.DutyToggle
api-version: 1.16
commands:
  onduty:
    description: Go on duty
  offduty:
    description: Go off duty
  onleave:
    description: Go on leave
  offleave:
    description: Go off leave
  staffstatus:
    description: View the currently online staff's status